### ISSUE TITLE
Action not working for Firefox latest

### ISSUE THREAD

**Issue by kriegaex** [abhi1693/setup-browser#8]
```text
Run abhi1693/setup-browser@v0.1.1
  with:
    browser: firefox
    version: latest
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/8.0.[2](https://github.com/kriegaex/GebSpockSamples/runs/5268719963?check_suite_focus=true#step:7:2)92-1/x64
Error: File not found: '/home/runner/work/_actions/abhi169[3](https://github.com/kriegaex/GebSpockSamples/runs/5268719963?check_suite_focus=true#step:7:3)/setup-browser/v0.1.1/index.js'
```

**Comment by abhi1693** [comment]
@kriegaex Thank you for reporting the issue. I have added the following versions for firefox

- latest
- latest-devedition
- latest-beta
- latest-esr

**Comment by kriegaex** [comment]
This does not seem to work either on Windows.

```text
Run abhi1693/setup-browser@v0.3.0
  with:
    browser: firefox
    version: latest
  env:
    JAVA_HOME: C:\hostedtoolcache\windows\Java_Adopt_jdk\8.0.3[2](https://github.com/kriegaex/GebSpockSamples/runs/5277311134?check_suite_focus=true#step:8:2)2-6\x64
Error: File not found: 'D:\a\_actions\abhi169[3](https://github.com/kriegaex/GebSpockSamples/runs/5277311134?check_suite_focus=true#step:8:3)\setup-browser\v0.3.0\index.js'
```

**Comment by abhi1693** [comment]
@kriegaex  Github closed the issue on its own when I merged the PR for Firefox on Linux.

Use `v0.3.1`, there was a binary path issue for windows with Firefox in the previous version.

You can check the build status at https://github.com/abhi1693/setup-browser/runs/5277424654?check_suite_focus=true

**Comment by kriegaex** [comment]
So what am I doing wrong? 
![Screenshot_20220222-003909_Chrome](https://user-images.githubusercontent.com/1537384/155004332-e16d833b-b006-46d0-a16e-da36663e7b3b.jpg)

**Comment by abhi1693** [comment]
@kriegaex I think the issue was caused by the missing `dist` directory. I have pushed it again to Github. Can you try now? If that does not work, can you try with `main`?

**Comment by kriegaex** [comment]
```none
Run abhi1693/setup-browser@main
  with:
    browser: firefox
    version: latest
  env:
    JAVA_HOME: C:\hostedtoolcache\windows\Java_Adopt_jdk\8.0.3[2](https://github.com/kriegaex/GebSpockSamples/runs/5281529255?check_suite_focus=true#step:8:2)2-6\x64
Error: File not found: 'D:\a\_actions\abhi169[3](https://github.com/kriegaex/GebSpockSamples/runs/5281529255?check_suite_focus=true#step:8:3)\setup-browser\main\index.js'
```

What I do not understand is: Why do your own tests not cover that? Why are you burning version numbers and using me as your guinea pig instead of testing this yourself? Trial & error is not a good strategy for software development, if there are good and obvious alternatives like in this case.
